Remove properties that conflict with jx version (#12)
Due to
```
k logs jenkins-x-jxui-84748899c6-vzq94 -c jxui-backend
error: error getting Requirements from TeamSettings to determine if in GitHub app mode: validation failures in requirements from team settings:
velero: Additional property schedule is not allowed
velero: Additional property ttl is not allowed
cluster: Additional property devEnvApprovers is not allowed
```